POST http://localhost:3000/users
content-type: application/json

{
  "name": "evan",
  "email": "evan@evan.evan",
  "password": "password",
  "password_confirmation": "password"
}

### Log In Victoria
POST http://localhost:3000/sessions
content-type: application/json

{
  "email": "visforvictoria@v.com",
  "password": "password"
}

### Create Dog Evan
POST http://localhost:3000/dogs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDc5Nzk1Njl9.LGI9EPpOrfbF-2HfN0qut7VMxe42JI_YiQd1yfO09hE
content-type: application/json

{
  "name": "Buttercup",
  "age": 17,
  "breed": "teacup poodle"
}

### Delete Dog Evan
DELETE http://localhost:3000/dogs/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDc5Nzk1Njl9.LGI9EPpOrfbF-2HfN0qut7VMxe42JI_YiQd1yfO09hE

### Update Dog Evan
PATCH http://localhost:3000/dogs/6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDc5Nzk1Njl9.LGI9EPpOrfbF-2HfN0qut7VMxe42JI_YiQd1yfO09hE
content-type: application/json

{
  "name": "Tinkerbell",
  "age": "18",
  "breed": "toy poodle"
}

### Index Evan
GET http://localhost:3000/dogs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDc5Nzk1Njl9.LGI9EPpOrfbF-2HfN0qut7VMxe42JI_YiQd1yfO09hE
